version: '3'

services:

  update:
    build:
      dockerfile: ./Dockerfile
      context: ./
    volumes:
      - ./gen:/gen
      - ./entrypoint.sh:/workspace/entrypoint.sh
    command: ["sh", "./entrypoint.sh"]

  schema:
    build:
      dockerfile: ./schema/Dockerfile
      #context: ./schema/
    volumes:
      - ./gen:/workspace/gen
      - ./schema:/workspace/schema
    command: ["sh", "./entrypoint.sh"]
