name: Schema check
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check schema
        run: docker compose up --build schema
